
stages:          
  - build

build-job:       
  stage: build
  tags:
    - grh
  only:
    - main
  script:
    - date
    - pwd
    - ls -la
    - node -v
    - npm install
    - composer install

  
