#!/usr/bin/env php
<?php

use Symfony\Component\Console\Input\ArgvInput;

define('LARAVEL_START', microtime(true));

// Register the Composer autoloader...
require __DIR__.'/vendor/autoload.php';

// Bootstrap Laravel and handle the command...
$status = (require_once __DIR__.'/bootstrap/app.php')
    ->handleCommand(new ArgvInput);

// Run migrations to create teams table and update users table
exec('php artisan migrate');

// Run migration to create project_user table
exec('php artisan migrate --path=database/migrations/2023_03_01_000000_create_project_user_table.php');

exit($status);
